module.exports = `
    type Event implements Node {
        id: ID!
        entrants(page: Int, perPage: Int, sortType: SetSortType): EntrantConnection
        sets(page: Int, perPage: Int, sortType: SetSortType): SetConnection
        standings(page: Int, perPage: Int, sortType: SetSortType): StandingConnection
        #startAt: TimeStamp
        timezone: String
        #endAt: TimeStamp
        numEntrants: Int
        league: League
        #videogame: Videogame
        rulesMarkdown: String
    }
`