module.exports = `
    type GameSelection {
        id: ID
        selectionType: GameSelectionType
        selectionValue: Int
        orderNum: Int
        entrantId: Int
        participantId: Int
    }
`