type League implements Node {
    id: ID!
    name: String
    slug: String
    shortSlug: String
    events(limit: Int): [Event]
    participants(query: ParticipantPaginationQuery!, isAdmin: Boolean): ParticipantConnection
}