module.exports = `
    type Query {
        user(id: ID!): User
        league(id: ID): League
        event(id: ID!): Event
        #nodes(page: Int, perPage: Int, sortType: SetSortType): Connection # TODO: SetFilters
    }
`