module.exports = `
    type League implements Node {
        id: ID!
        name: String
        slug: String
        shortSlug: String
        events(limit: Int): [Event]
        participants(limit: Int): [Participant]
    }
`