module.exports = `
    type Mutation {
        # User
        createUser(name: String): User

        # League
        createLeague(name: String): User

        # Event
        createEvent(name: String, leagueId: ID!): User
    }
`